### ISSUE TITLE
SRT Support 

### ISSUE THREAD

**Issue by gedw99** [pion/ion#526]
##
## Motivation

video cameras from most makers now support the SRT protocol to allow a camera person to stream directly to ION and then Ion to publish to users over webRTC.

Why are we doing this? What use cases does it support? What is the expected outcome? Is this available in other implementations? Can this not be implemented using primitives?

It would allow users to do real rooms Mixing of video streams in a similar way to OBS and Allison allow ION to be used by film and video production companies and maybe attract more funding etc too.

https://github.com/Haivision/srt

https://github.com/Haivision/srtgo

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered.

## Additional context

The golang lib for SRT is from the org that invented this open standard.

the only difference between srp and webrtc is that SRT is designed for higher quality. 

SRT is pretty much the only open standard for doing streaming from high quality production cameras. 
Because of its open licensing Sony, JVC and many others are supporting it in all cameras coming out for the last year

**Comment by cloudwebrtc** [comment]
Good idea, but I don’t know how to start, how to convert an srt stream to rtp

**Comment by gedw99** [comment]
@cloudwebrtc 

Not sure this helps ?
https://github.com/SRTLab/srt-cookbook/blob/master/docs/apps/ffmpeg.md

**Comment by gedw99** [comment]
@cloudwebrtc this one uses pion webrtc and srtgo together, so you might get some insight from it

https://github.com/erdnaxe/ghostream/blob/dev/go.mod
